"use client";

import * as React from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import CircularProgress from "@mui/material/CircularProgress";
import Collapse from "@mui/material/Collapse";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import Divider from "@mui/material/Divider";
import MenuItem from "@mui/material/MenuItem";
import Paper from "@mui/material/Paper";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";
import RestaurantMenuIcon from "@mui/icons-material/RestaurantMenu";
import { MENU_CATEGORIES, filterMenuMeals, foodGroupFor, loadMenuMeals, macroProfileFor, nutritionProfileFor, sortMenuMeals, type FoodGroup, type MacroProfile, type MenuFilters, type MenuSort, type NutritionProfile } from "@/lib/menu";
import { getActivePlan, todayKey, updateActivePlan } from "@/lib/storage";
import { planDayIndex } from "@/lib/progress";
import { usePlanStore } from "@/lib/usePlanStore";
import type { ResearchedMeal } from "@/lib/types";

const FOOD_GROUPS: FoodGroup[] = ["Fish & seafood", "Fruit-forward", "Vegetables & legumes", "Poultry", "Meat", "Pasta & grains", "Soups & stews", "Sweets & baking", "Eggs & dairy", "Mixed dishes"];
const MACRO_PROFILES: MacroProfile[] = ["Protein-led", "Carb-led", "Fat-led", "Macro-balanced"];
const NUTRITION_PROFILES: NutritionProfile[] = ["Lighter", "Protein-rich", "Balanced", "Rich / occasional"];
const EMPTY_FILTERS: MenuFilters = { search: "", region: "", category: "", foodGroup: "", macroProfile: "", nutritionProfile: "" };

function MenuDishCard({ meal, actionLabel, onChoose }: { meal: ResearchedMeal; actionLabel: string; onChoose: (meal: ResearchedMeal) => void }) {
  const [open, setOpen] = React.useState(false);
  const detailsId = `menu-dish-${meal.name.replace(/\W+/g, "-").toLowerCase()}`;
  return <Paper variant="outlined" sx={{ overflow: "hidden", display: "flex", flexDirection: "column" }}>
    <Box component="img" src={meal.imageUrl} alt={meal.name} loading="lazy" sx={{ width: "100%", aspectRatio: "16 / 9", objectFit: "cover", bgcolor: "action.hover" }} />
    <Box sx={{ p: 2, display: "flex", flexDirection: "column", gap: 1.25, flexGrow: 1 }}>
      <Box><Typography variant="h6" sx={{ fontWeight: 700, lineHeight: 1.2 }}>{meal.name}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>{meal.origin || "Unknown region"} · {meal.category || "Uncategorised"}</Typography></Box>
      <Box sx={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 0.75 }}>{[[meal.calories, "kcal"], [meal.proteinG, "protein"], [meal.carbsG ?? 0, "carbs"], [meal.fatG ?? 0, "fat"]].map(([value, label]) => <Box key={label} sx={{ textAlign: "center", bgcolor: "action.hover", borderRadius: 1, py: 0.75, px: 0.25 }}><Typography variant="body2" sx={{ fontWeight: 700 }}>{value}</Typography><Typography variant="caption" color="text.secondary">{label}{label === "kcal" ? "" : " g"}</Typography></Box>)}</Box>
      <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.75 }}><Chip size="small" color="primary" variant="outlined" label={foodGroupFor(meal)} /><Chip size="small" variant="outlined" label={macroProfileFor(meal)} /><Chip size="small" color={nutritionProfileFor(meal) === "Rich / occasional" ? "warning" : "success"} variant="outlined" label={nutritionProfileFor(meal)} /></Box>
      <Box sx={{ display: "flex", gap: 1, mt: "auto", flexWrap: "wrap" }}><Button size="small" variant="contained" onClick={() => onChoose(meal)}>{actionLabel}</Button><Button size="small" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls={detailsId} endIcon={<ExpandMoreIcon sx={{ transform: open ? "rotate(180deg)" : "none", transition: "transform 150ms" }} />}>{open ? "Hide details" : "Explore dish"}</Button>{meal.sourceUrl && <Button size="small" href={meal.sourceUrl} target="_blank" rel="noopener noreferrer" endIcon={<OpenInNewIcon />}>Source</Button>}</Box>
    </Box>
    <Collapse in={open} unmountOnExit><Box id={detailsId} sx={{ px: 2, pb: 2 }}><Divider sx={{ mb: 1.5 }} /><Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 0.75 }}>Ingredients</Typography><Box component="ul" sx={{ m: 0, pl: 2.5, mb: 1.5 }}>{meal.mealIngredients.map((ingredient) => <Typography component="li" variant="body2" key={`${ingredient.name}-${ingredient.measure}`}>{ingredient.display}</Typography>)}</Box>{meal.steps?.length ? <><Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 0.75 }}>Method</Typography><Box component="ol" sx={{ m: 0, pl: 2.5 }}>{meal.steps.map((step, index) => <Typography component="li" variant="body2" key={index} sx={{ mb: 0.5 }}>{step}</Typography>)}</Box></> : null}<Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 1.5 }}>Nutrition is per assumed serving and summed from USDA measurements. Coverage: {Math.round(meal.nutritionCoverage * 100)}%.</Typography></Box></Collapse>
  </Paper>;
}

export default function MenuExplorer() {
  const router = useRouter(); const searchParams = useSearchParams(); const store = usePlanStore(); const active = getActivePlan(store);
  const [meals, setMeals] = React.useState<ResearchedMeal[]>([]); const [filters, setFilters] = React.useState<MenuFilters>(EMPTY_FILTERS); const [sort, setSort] = React.useState<MenuSort>("name"); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [visibleCount, setVisibleCount] = React.useState(12); const [scheduleMeal, setScheduleMeal] = React.useState<ResearchedMeal | null>(null); const [scheduleDay, setScheduleDay] = React.useState("0"); const [scheduleSlot, setScheduleSlot] = React.useState("0");
  const replacementDay = Number(searchParams.get("replaceDay")); const replacementSlot = Number(searchParams.get("replaceMeal")); const replacementTarget = active && Number.isInteger(replacementDay) && Number.isInteger(replacementSlot) ? active.plan.days[replacementDay]?.meals[replacementSlot] ?? null : null;
  const retry = React.useCallback(() => { setLoading(true); setError(null); loadMenuMeals().then(setMeals).catch(() => setError("The recipe catalogue could not be loaded. Please try again.")).finally(() => setLoading(false)); }, []);
  React.useEffect(() => { let cancelled = false; loadMenuMeals().then((loaded) => { if (!cancelled) setMeals(loaded); }).catch(() => { if (!cancelled) setError("The recipe catalogue could not be loaded. Please try again."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const regions = React.useMemo(() => [...new Set(meals.map((meal) => meal.origin).filter((value): value is string => Boolean(value)))].sort(), [meals]);
  const filtered = React.useMemo(() => sortMenuMeals(filterMenuMeals(meals, filters), sort), [filters, meals, sort]);
  const equivalent = React.useMemo(() => { if (!replacementTarget) return filtered; const score = (meal: ResearchedMeal) => Math.abs(meal.calories - replacementTarget.calories) / Math.max(replacementTarget.calories, 1) + Math.abs(meal.proteinG - replacementTarget.proteinG) / Math.max(replacementTarget.proteinG, 8) + Math.abs((meal.carbsG ?? 0) - (replacementTarget.carbsG ?? 0)) / Math.max(replacementTarget.carbsG ?? 8, 8) + Math.abs((meal.fatG ?? 0) - (replacementTarget.fatG ?? 0)) / Math.max(replacementTarget.fatG ?? 5, 5); return filtered.filter((meal) => meal.name !== replacementTarget.name).sort((a, b) => score(a) - score(b)); }, [filtered, replacementTarget]);
  const updateFilter = (key: keyof MenuFilters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setVisibleCount(12); };
  const replaceSlot = (meal: ResearchedMeal, day: number, slot: number) => { if (!active || !active.plan.days[day]?.meals[slot]) return; const days = active.plan.days.map((planDay, index) => index === day ? { ...planDay, meals: planDay.meals.map((current, mealIndex) => mealIndex === slot ? meal : current) } : planDay); const checks = { ...active.checks }; if (day === planDayIndex() && checks[todayKey()]) { const next = [...checks[todayKey()]]; next[slot] = false; checks[todayKey()] = next; } updateActivePlan(store, { plan: { ...active.plan, days }, checks }); };
  const choose = (meal: ResearchedMeal) => { if (replacementTarget) { replaceSlot(meal, replacementDay, replacementSlot); router.push("/"); } else setScheduleMeal(meal); };
  const schedule = () => { if (scheduleMeal) replaceSlot(scheduleMeal, Number(scheduleDay), Number(scheduleSlot)); setScheduleMeal(null); router.push("/"); };
  const timeName = (slot: number, total: number) => total === 1 ? "Meal" : slot === 0 ? "Breakfast" : slot === total - 1 ? "Dinner" : slot === 1 ? "Lunch" : `Meal ${slot + 1}`;
  const hasFilters = Object.values(filters).some(Boolean);
  return <Box sx={{ display: "grid", gap: 3 }}>
    <Box><Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}><RestaurantMenuIcon color="primary" fontSize="large" /><Typography variant="h3" component="h1" sx={{ fontWeight: 800, fontSize: { xs: "2rem", sm: "3rem" } }}>{replacementTarget ? "Choose a replacement" : "Explore the menu"}</Typography></Box><Typography color="text.secondary" sx={{ maxWidth: 720 }}>{replacementTarget ? `Pick a replacement for ${replacementTarget.name}. Results are ranked by the closest calories, protein, carbs, and fat.` : "Browse real dishes from around the world—from lighter everyday meals to rich desserts and comfort food. Filter by what matters to you, then open any dish for its ingredients and method."}</Typography></Box>
    {replacementTarget && <Alert severity="info" action={<Button color="inherit" onClick={() => equivalent.length && choose(equivalent[Math.floor(Math.random() * Math.min(equivalent.length, 8))])}>Choose a random equivalent</Button>}>Replacing {replacementTarget.name} ({replacementTarget.calories} kcal · {replacementTarget.proteinG} g protein). You can also choose a listed dish.</Alert>}
    <Alert severity="info" variant="outlined">“Lighter,” “balanced,” and “rich / occasional” are comparison groups based on calories, fat, protein share, and recipe category—not medical advice or a moral judgment about food.</Alert>
    <Paper variant="outlined" sx={{ p: { xs: 2, sm: 2.5 } }}><Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>Find your next dish</Typography><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", md: "repeat(3, 1fr)" }, gap: 1.5 }}><TextField label="Search dishes or ingredients" value={filters.search} onChange={(event) => updateFilter("search", event.target.value)} sx={{ gridColumn: { sm: "1 / -1", md: "span 2" } }} /><TextField select label="Sort by" value={sort} onChange={(event) => setSort(event.target.value as MenuSort)}>{([['name','Dish name A–Z'],['region','Region A–Z'],['category','Category A–Z'],['calories-low','Calories: low to high'],['calories-high','Calories: high to low'],['protein-high','Protein: highest first'],['carbs-high','Carbs: highest first'],['fat-high','Fat: highest first']] as const).map(([value,label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><TextField select label="Region" value={filters.region} onChange={(event) => updateFilter("region", event.target.value)}><MenuItem value="">All regions</MenuItem>{regions.map((region) => <MenuItem key={region} value={region}>{region}</MenuItem>)}</TextField><TextField select label="Recipe category" value={filters.category} onChange={(event) => updateFilter("category", event.target.value)}><MenuItem value="">All categories</MenuItem>{MENU_CATEGORIES.map((category) => <MenuItem key={category} value={category}>{category}</MenuItem>)}</TextField><TextField select label="Food group" value={filters.foodGroup} onChange={(event) => updateFilter("foodGroup", event.target.value)}><MenuItem value="">All food groups</MenuItem>{FOOD_GROUPS.map((group) => <MenuItem key={group} value={group}>{group}</MenuItem>)}</TextField><TextField select label="Dominant macro" value={filters.macroProfile} onChange={(event) => updateFilter("macroProfile", event.target.value)}><MenuItem value="">Any macro profile</MenuItem>{MACRO_PROFILES.map((profile) => <MenuItem key={profile} value={profile}>{profile}</MenuItem>)}</TextField><TextField select label="Nutrition style" value={filters.nutritionProfile} onChange={(event) => updateFilter("nutritionProfile", event.target.value)}><MenuItem value="">All nutrition styles</MenuItem>{NUTRITION_PROFILES.map((profile) => <MenuItem key={profile} value={profile}>{profile}</MenuItem>)}</TextField></Box><Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 2, mt: 2, flexWrap: "wrap" }}><Typography variant="body2" color="text.secondary" aria-live="polite">{loading ? "Researching the menu…" : `${equivalent.length} dish${equivalent.length === 1 ? "" : "es"} found`}</Typography>{hasFilters && <Button size="small" onClick={() => setFilters(EMPTY_FILTERS)}>Clear filters</Button>}</Box></Paper>
    {loading && <Box sx={{ minHeight: 280, display: "grid", placeItems: "center", textAlign: "center" }}><Box><CircularProgress /><Typography color="text.secondary" sx={{ mt: 1 }}>Matching published recipes to USDA nutrition…</Typography></Box></Box>}{error && <Alert severity="error" action={<Button color="inherit" onClick={retry}>Retry</Button>}>{error}</Alert>}{!loading && !error && equivalent.length === 0 && <Paper variant="outlined" sx={{ p: 5, textAlign: "center" }}><Typography variant="h6" sx={{ fontWeight: 700 }}>No dishes match that combination</Typography><Typography color="text.secondary" sx={{ mt: 0.5, mb: 2 }}>Try removing one filter or searching for a broader ingredient.</Typography><Button variant="outlined" onClick={() => setFilters(EMPTY_FILTERS)}>Show the full menu</Button></Paper>}{!loading && !error && equivalent.length > 0 && <><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, minmax(0, 1fr))" }, gap: 2 }}>{equivalent.slice(0, visibleCount).map((meal) => <MenuDishCard key={`${meal.name}-${meal.origin}`} meal={meal} onChoose={choose} actionLabel={replacementTarget ? "Use as replacement" : "Schedule dish"} />)}</Box>{visibleCount < equivalent.length && <Button variant="outlined" size="large" onClick={() => setVisibleCount((count) => count + 12)} sx={{ justifySelf: "center" }}>Show more dishes</Button>}</>}
    <Dialog open={Boolean(scheduleMeal)} onClose={() => setScheduleMeal(null)} fullWidth maxWidth="xs"><DialogTitle>Schedule {scheduleMeal?.name}</DialogTitle><DialogContent sx={{ display: "grid", gap: 2, pt: "16px !important" }}>{!active ? <Alert severity="warning">Create a diet plan before scheduling a dish.</Alert> : <><Typography variant="body2" color="text.secondary">Choose the day and time slot this dish should replace.</Typography><TextField select label="Day" value={scheduleDay} onChange={(event) => { setScheduleDay(event.target.value); setScheduleSlot("0"); }}>{active.plan.days.map((day, index) => <MenuItem key={day.day} value={index}>{day.day}</MenuItem>)}</TextField><TextField select label="Time" value={scheduleSlot} onChange={(event) => setScheduleSlot(event.target.value)}>{active.plan.days[Number(scheduleDay)]?.meals.map((meal, index, all) => <MenuItem key={`${index}-${meal.name}`} value={index}>{timeName(index, all.length)} · {meal.name}</MenuItem>)}</TextField></>}</DialogContent><DialogActions><Button onClick={() => setScheduleMeal(null)}>Cancel</Button><Button variant="contained" onClick={schedule} disabled={!active}>Schedule dish</Button></DialogActions></Dialog>
  </Box>;
}
